AIM 
To develop the standard of living of every member through financial freedom 

OBJESTIVES 
 ```1. To develop members saving mentality through encouragement and enlightment on the power of small saving in order to raise a good capital for business and to embark on a good project

2. To ease the financial burden of every member by providing loans with low interest for every member who need capital to start/boost a business.

3. To ensure that all member is making profit base on their savings according to the profit/load sharing ratio of the association 

4. To celebrate and render financial assistance ( base on the constitution of the association ) to every member during their ceremony. 

REGULATION 
This association is programme to be digital as all our activities will be carried out remotely/ online. These include:
A-Member's registration 
B-membership Identity Card 
C-membership pass book
D-genera book-keeping such as weekly, monthly and annual recording
E-financial transaction like Loans, savings, dues, fines, gift and others will be strictly on transfer 


RULES
I: Every member must fill their data form and Submit to association platform 

II: All member must be present at every meeting schedule to hold on the platform 

III: Each member is expected to pay at least a sum of one thousand (1000) weekly to the association account to serve as individual saving and capital for the association starting from 1st week of September 2022 to last week of December 2022. 

IV:All proof of payment must be forward to association platform for proper recording 

V: A platform will be open for interested member to apply for loan not more than times two of their savings. This will commence on the 1st week of January 2023

VI; Every approved loan from January to June 2023 will attract interest of 5% payable within 3 months and 10% payable within 6 months

VII: A guarantor will be required from any member who is interest in taking loan and such guarantor must be a member. 

VIII: Every member will be paying their weekly savings into a personal account of a trusted member temporary before the registration and opening of account of the association which is expected to be done before 31st of December 2o22.

NOTE: This constitution will be review immediately after the registration of the association with C.A.C

```
